#!/bin/sh

if (( "$#" != 1 ))
then
	echo "Usage: ${0##*/} sitename (e.g. ${0##*/} mysite.co.uk)"
	exit 1
fi

live=$1
dev=${live/.co.uk/.dev}
dev=${dev/.com/.dev}
dev=${dev/.net/.dev}
dev=${dev/.org/.dev}

createvhost $dev $live
cd $HOME/Dropbox/Sites/$live
installwp
createdb $live

echo Wordpress site created.

editsite $live