#!/bin/sh

if (( "$#" != 2 ))
then
	echo "Usage: ${0##*/} OldName NewName (e.g. ${0##*/} Database1 Database2)"
	exit 1
fi

MYSQLPARAMS="-uroot -proot"
/Applications/MAMP/Library/bin/mysql $MYSQLPARAMS $1 -e "SELECT 1" > /dev/null || exit 1
/Applications/MAMP/Library/bin/mysql -e "CREATE DATABASE \`$2\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;" $MYSQLPARAMS
for i in $(/Applications/MAMP/Library/bin/mysql -Ns $1 -e "show tables" $MYSQLPARAMS);do
  echo "$1.$i -> $2.$i"
  /Applications/MAMP/Library/bin/mysql -e "RENAME TABLE \`$1\`.\`$i\` to \`$2\`.\`$i\`" $MYSQLPARAMS || exit 1
done
/Applications/MAMP/Library/bin/mysql -e "DROP DATABASE \`$1\`" $MYSQLPARAMS || exit 1

echo Database renamed.