#!/bin/sh

if (( "$#" != 1 ))
then
	echo "Usage: ${0##*/} sitename (e.g. ${0##*/} mysite.co.uk)"
	exit 1
fi

osascript <<EOD

tell application "Transmit"
	set myFave to item 1 of (favorites whose name is "$1")
	tell current tab of (make new document at end)
		connect to myFave
	end tell
end tell

EOD

echo Transmit launched.